export const SET_SINGER = 'SET_SINGER'

export const SET_PLAYING = 'SET_PLAYING'

export const SET_FULLSCREEN = 'SET_FULLSCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCELIST = 'SET_SEQUENCELIST'

export const SET_PLAYMODE = 'SET_PLAYMODE'

export const SET_CURRENINDEX = 'SET_CURRENINDEX'

export const SET_PLAYLISTINFO = 'SET_PLAYLISTINFO'

export const SET_TOPLISTINFO = 'SET_TOPLISTINFO'

export const SET_FAVOURITELIST = 'SET_FAVOURITELIST'

export const SET_LATELYLIST = 'SET_LATELYLIST'